package de.dzl.lelantus;

import java.util.Base64;

public interface Encoder extends CodingSystem {
	/**
	 * Get the number of bytes (array length) returned by
	 * the respective encode functions.
	 * @return length of byte array
	 */
	public int getCodeLength();

	/**
	 * Convert the generated code to a string representation.
	 * @param code code generated by this encoder
	 * @return string representation of code
	 */
	public default String convertToString(byte[] code) {
		return Base64.getEncoder().encodeToString(code);
	}
	/**
	 * Convert a string previously converted via {@link #convertToString(byte[])}
	 * back to it's original byte array representation.
	 * @param code string representation
	 * @return original byte code
	 */
	public default byte[] convertToCode(String code) {
		return Base64.getDecoder().decode(code);
	}

}
